## The number of HTTP 5XX server error codes that originate from the load balancer.
## This count does not include any response codes generated by the targets.

resource "aws_cloudwatch_metric_alarm" "this" { 
    alarm_name          = "alb-alarm"
    alarm_description   = "This metric monitors number of 5xx erros in the application load balancer"
    comparison_operator = "GreaterThanOrEqualToThreshold"
    evaluation_periods  = 1
    threshold           = 10
    period              = 60
    namespace   = "AWS/ApplicationELB"
    metric_name = "HTTPCode_ELB_5XX_Count"
    statistic   = "Sum"
    alarm_actions = [aws_sns_topic.notify_user.arn]
    
    dimensions = {
       TargetGroup = "arn:aws:elasticloadbalancing:us-west-1:915862570768:targetgroup/tf-20231022052937185300000002/34e1753630986d2c"
       LoadBalancer = "my-alb-1794335587.us-west-1.elb.amazonaws.com"
   }   
}
